add extra line to Rprofile
This avoids a common error from MRAN installations

```
 Error: Failed to install 'sitrep' from GitHub:
  Failed to install 'linelist' from GitHub:
  (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'
```

It's common for MRAN to include a CRANextra URL that has links to packages that need some special treatment for installation.